# Generated by Django 4.0.6 on 2022-07-30 18:38

import uuid

import django.db.models.deletion
from django.db import migrations, models

import app.models.fields.enum
import app.models.subreddit.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "queue",
            },
        ),
        migrations.CreateModel(
            name="Subreddit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, default=None, max_length=7, null=True),
                ),
                ("icon_url", models.URLField(blank=True, default=None, null=True)),
                ("id", models.CharField(blank=True, max_length=100, null=True)),
                ("nsfw", models.BooleanField(default=False)),
                ("quarantined", models.BooleanField(default=False)),
                ("subscribers", models.IntegerField(default=0)),
                ("title", models.TextField(blank=True, null=True)),
                (
                    "type",
                    app.models.fields.enum.EnumField(
                        app.models.subreddit.enums.SubredditType,
                        default=app.models.subreddit.enums.SubredditType["PUBLIC"],
                        max_length=12,
                    ),
                ),
            ],
            options={
                "db_table": "subreddits",
            },
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    app.models.fields.enum.EnumField(
                        app.models.link.enums.LinkType,
                        default=None,
                        max_length=7,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sources",
                        to="app.subreddit",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="targets",
                        to="app.subreddit",
                    ),
                ),
            ],
            options={
                "db_table": "relations",
            },
        ),
    ]
