# Generated by Django 4.0.6 on 2022-07-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subreddit",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="subscribers",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
