# Generated by Django 4.0.6 on 2022-07-30 18:05

from django.db import migrations

import app.models.fields.enum
import app.models.subreddit.enums


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subreddit",
            name="name",
        ),
        migrations.AlterField(
            model_name="relation",
            name="type",
            field=app.models.fields.enum.EnumField(
                app.models.relation.enums.RelationType, default=None, max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="type",
            field=app.models.fields.enum.EnumField(
                app.models.subreddit.enums.SubredditType,
                default=app.models.subreddit.enums.SubredditType["PUBLIC"],
                max_length=12,
            ),
        ),
    ]
