# Generated by Django 4.0.6 on 2022-07-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_subreddit_name_alter_relation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subreddit",
            name="color",
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="subreddit",
            name="icon_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="subreddit",
            name="name",
            field=models.CharField(default="name", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subreddit",
            name="nsfw",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subreddit",
            name="quarantined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subreddit",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="subscribers",
            field=models.IntegerField(default=0),
        ),
    ]
