# Generated by Django 4.0.6 on 2022-07-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_subreddit_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subreddit",
            old_name="updated_at",
            new_name="last_update",
        ),
    ]
