# Generated by Django 4.0.6 on 2022-07-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_updated_at_subreddit_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subreddit",
            name="nsfw",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="quarantined",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
