# Generated by Django 4.0.6 on 2022-07-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_subreddit_nsfw_alter_subreddit_quarantined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="source",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="relation",
            name="target",
            field=models.CharField(max_length=100),
        ),
    ]
