# Generated by Django 4.0.6 on 2022-07-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_relation_source_alter_relation_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="name",
            field=models.CharField(
                max_length=25, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="id",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="source",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="relation",
            name="target",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="name",
            field=models.CharField(
                max_length=25, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
