# Generated by Django 4.0.6 on 2022-07-30 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_relation_id_relation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=36, primary_key=True, serialize=False
            ),
        ),
    ]
