# Generated by Django 4.0.6 on 2022-07-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_relation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="version",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subreddit",
            name="version",
            field=models.IntegerField(default=0),
        ),
    ]
