# Generated by Django 4.0.6 on 2022-08-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_relation_version_subreddit_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="subreddit",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
