# Generated by Django 4.0.6 on 2022-08-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_subreddit_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="subreddit",
            name="banner_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
