# Generated by Django 4.0.6 on 2022-08-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_subreddit_banner_url_alter_subreddit_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subreddit",
            old_name="banner_url",
            new_name="img_banner",
        ),
        migrations.RenameField(
            model_name="subreddit",
            old_name="icon_url",
            new_name="img_icon",
        ),
    ]
