# Generated by Django 4.0.6 on 2022-08-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_rename_banner_url_subreddit_img_banner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subreddit",
            name="img_header",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
