# Generated by Django 4.0.6 on 2022-08-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_rename_last_update_subreddit_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subreddit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
