# Generated by Django 4.0.6 on 2022-08-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_subreddit_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subreddit",
            name="subscribers",
            field=models.IntegerField(default=0),
        ),
    ]
