# Generated by Django 4.0.6 on 2022-08-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_subreddit_nsfw_alter_subreddit_quarantined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subreddit",
            name="subscribers",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
