# Generated by Django 4.0.6 on 2022-08-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_queue_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
    ]
