# Generated by Django 4.0.6 on 2022-08-12 17:42

from django.db import migrations

import app.models.fields.enum
import app.models.subreddit.enums


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_queue_created_at_alter_queue_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subreddit",
            name="type",
            field=app.models.fields.enum.EnumField(
                app.models.subreddit.enums.SubredditType,
                default=app.models.subreddit.enums.SubredditType["PUBLIC"],
                max_length=14,
            ),
        ),
    ]
