# Generated by Django 4.0.6 on 2022-08-16 17:47

from django.db import migrations, models

import app.models.fields.enum
import app.models.link.enums


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_subreddit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="subreddit",
            name="new",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="relation",
            name="type",
            field=app.models.fields.enum.EnumField(
                app.models.link.enums.LinkType, default=None, max_length=11
            ),
        ),
    ]
