# Generated by Django 4.0.6 on 2022-08-17 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_subreddit_new_alter_relation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=25, null=True
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "errors",
            },
        ),
    ]
