# Generated by Django 4.0.6 on 2022-09-17 17:03

import app.models.fields.enum
import app.models.subreddit.enums
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_error"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Relation",
            new_name="Link",
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="type",
            field=app.models.fields.enum.EnumField(
                app.models.subreddit.enums.SubredditType,
                default=app.models.subreddit.enums.SubredditType["PUBLIC"],
                max_length=12,
            ),
        ),
        migrations.AlterModelTable(
            name="link",
            table="links",
        ),
    ]
